[build]
  command   = "npm run build && npm run export"  # your build command
  publish   = "out"                               # folder to deploy (for static export)
  functions = "netlify/functions"                # optional, for serverless functions

[plugins]
    package = "@netlify/plugin-nextjs"
